[build]
  command = "npm run build"
  functions = "functions-build"
  publish = "public"

[dev]
  command = "npm run dev"
  targetPort = 8888

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
